version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: latest-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn reg-suit run
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            context: example-reg-suit-workflow

